### PR TITLE
add persian language

### PR DESCRIPTION
**Pull request by eshagh79**
Hi, I translated some of this program.
I changed the following files:
app/src/main/res/values-fa/strings.xml
metadata/fa_IR/full_description.txt
metadata/fa_IR/short_description.txt

And I did not change the rest of the files, but since I do not know if the rest of the files are needed or not, I copied them all. (metadata/fa_IR/ Folder)

If I got it wrong, please tell me.
And that the Persian translation is not yet complete, but will be completed soon

### CODE REVIEW

**Comment by gujjwal00** [comment]
It is not necessary to copy every file to `metadata/fa_IR/` folder. F-Droid will automatically fallback to `metadata/en-US/` if a particular item is missing from `metadata/fa_IR/`. So you can remove the extra files, and only keep the files you are actually translating.

And thanks for contributing.

**Comment by gujjwal00** [comment]
Hi @eshagh79 , I have setup a Weblate project for AVNC: https://hosted.weblate.org/projects/avnc/
I am still waiting for final approval though.

 If you want, I can merge this PR in current state, and you can translate the remaining strings on Weblate, or you can finish it here.

PS: You should not waste you time translating old release notes, but I am fine with it if you want to.

**Comment by eshagh79** [comment]
It's a good idea, it's better to merge these translations. I continue to do translations on the weblate.

And I think there is a problem with a string. (An extra space)
On line 69:‍ `<string name="msg_key_compat_mode_help">Some servers don\'t support direct Unicode input. Compatibility Mode tries to send key events in legacy format. \n\nTry enabling/disabling this if you are having trouble entering some characters.</string>`
After "legacy format. " There is an extra space that has no effect because there is a new line after it.

**Comment by gujjwal00** [comment]
Removed extra space in https://github.com/gujjwal00/avnc/commit/bbd1c294d9f02b2904873b372852e3fcedf7683b.

Also, I am deleting `metadata/fa_IR/title.txt` from this PR, as app name is not translatable.

**Pull request merged**
